title: Nordic Minimalist Blog
description: A clean, minimalist blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krill11.github.io" # your site's URL

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor