title: My Blog
description: A simple black and white blog
baseurl: ""
url: "https://krill11.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true